export const mockData = {
  2: [
    {
      id: "1uUPANC3d6hK512yT9aq",
      awayNum: "15",
      homeNum: "12",
      awayName: "MF",
      time: {
        seconds: 1704895651,
        nanoseconds: 19000000,
      },
      homeName: "GRF",
      groupNum: "3",
      matchNum: "2",
    },
    {
      id: "2yIDZGCHCpsl3UqP3SXH",
      groupNum: "3",
      awayNum: "12",
      homeName: "MF",
      awayName: "TTF",
      homeNum: "21",
      time: {
        seconds: 1704894970,
        nanoseconds: 228000000,
      },
      matchNum: "2",
    },
    {
      id: "6nRcjn2d1gjtpLjJgUMe",
      matchNum: "2",
      homeName: "TTF",
      awayName: "PTF",
      awayNum: "18",
      groupNum: "3",
      time: {
        seconds: 1704895672,
        nanoseconds: 938000000,
      },
      homeNum: "7",
    },
    {
      id: "JrllmYEeBkbOESnqV55K",
      homeNum: "10",
      homeName: "FKIT",
      awayNum: "9",
      groupNum: "2",
      time: {
        seconds: 1704886495,
        nanoseconds: 789000000,
      },
      matchNum: "2",
      awayName: "PBF",
    },
    {
      id: "NWwoRvcvT5Z0KXMUhdec",
      matchNum: "2",
      awayName: "FFT",
      homeNum: "8",
      groupNum: "2",
      time: {
        seconds: 1704886572,
        nanoseconds: 150000000,
      },
      homeName: "PBF",
      awayNum: "8",
    },
    {
      id: "OSZSR2EpbcRBKvzQ1cMX",
      matchNum: "2",
      awayNum: "10",
      homeNum: "8",
      groupNum: "2",
      homeName: "FFT",
      time: {
        seconds: 1704886522,
        nanoseconds: 100000000,
      },
      awayName: "FKIT",
    },
    {
      id: "UKo7issxsIz1bMK9AX8M",
      homeNum: "19",
      time: {
        seconds: 1704895689,
        nanoseconds: 512000000,
      },
      groupNum: "3",
      awayName: "GRF",
      awayNum: "20",
      matchNum: "2",
      homeName: "PTF",
    },
    {
      id: "X3Kd7XINnCIbMyaOLPmR",
      homeNum: "19",
      awayNum: "7",
      groupNum: "2",
      homeName: "KTF",
      matchNum: "2",
      awayName: "FFT",
      time: {
        seconds: 1704886596,
        nanoseconds: 985000000,
      },
    },
    {
      id: "kgcG4KeSk5SdUlhA9N6L",
      awayNum: "8",
      homeName: "MF",
      matchNum: "2",
      awayName: "PTF",
      groupNum: "3",
      time: {
        seconds: 1704895615,
        nanoseconds: 869000000,
      },
      homeNum: "10",
    },
    {
      id: "pBuCjRdWij0jygJDgnx1",
      awayNum: "15",
      time: {
        seconds: 1704886049,
        nanoseconds: 80000000,
      },
      awayName: "KTF",
      groupNum: "2",
      homeName: "FKIT",
      matchNum: "2",
      homeNum: "12",
    },
    {
      id: "rK10iEJVMHOjvhgVC2wT",
      homeNum: "17",
      time: {
        seconds: 1704895706,
        nanoseconds: 364000000,
      },
      homeName: "TTF",
      awayNum: "17",
      groupNum: "3",
      matchNum: "2",
      awayName: "GRF",
    },
    {
      id: "zeU57MKv4nH5evfYYsnQ",
      awayNum: "12",
      homeName: "KTF",
      time: {
        seconds: 1704886552,
        nanoseconds: 721000000,
      },
      awayName: "PBF",
      groupNum: "2",
      matchNum: "2",
      homeNum: "18",
    },
  ],
  3: [
    {
      id: "9xx9QXc3UVVm0FDINSAg",
      groupNum: null,
      awayName: "FFT",
      matchNum: "3",
      time: {
        seconds: 1704982124,
        nanoseconds: 0,
      },
      homeNum: "8",
      awayNum: "9",
      homeName: "TTF",
    },
  ],
  4: [
    {
      id: "fIVBcPopIrs5NRd4ZstT",
      homeNum: "12",
      matchNum: "4",
      awayName: "PTF",
      groupNum: null,
      awayNum: "9",
      time: {
        seconds: 1705069682,
        nanoseconds: 82000000,
      },
      homeName: "PBF",
    },
  ],
  5: [
    {
      id: "3eqnCwDOxOnME7JC2Ncp",
      awayNum: "11",
      homeName: "KTF",
      homeNum: "12",
      time: {
        seconds: 1705156138,
        nanoseconds: 0,
      },
      matchNum: "5",
      awayName: "GRF",
      groupNum: null,
    },
    {
      id: "Zhww6tyGCxgAVMhLtOEw",
      homeNum: "10",
      awayNum: "11",
      groupNum: null,
      matchNum: "5",
      awayName: "MF",
      homeName: "FKIT",
      time: {
        seconds: 1705156306,
        nanoseconds: 921000000,
      },
    },
  ],
  6: [
    {
      id: "ZgGMMcW4jeiY3419SJuC",
      homeName: "FKIT",
      time: {
        seconds: 1705242733,
        nanoseconds: 36000000,
      },
      awayName: "GRF",
      awayNum: "8",
      homeNum: "9",
      groupNum: null,
      matchNum: "6",
    },
  ],
  7: [
    {
      id: "YtYOJ3Q5vXzJGGvmiZ1w",
      matchNum: "7",
      homeNum: "14",
      awayNum: "11",
      groupNum: null,
      time: {
        seconds: 1705329300,
        nanoseconds: 859000000,
      },
      awayName: "KTF",
      homeName: "MF",
    },
  ],
};
